// 03-reactthree/src/components/Canvas.jsx
import * as THREE from "three";
import { useRef, useEffect } from 'react';

function Canvas() {
    // 获取元素
    const oCanvas = useRef(null)
    useEffect(() => { 
        const { innerWidth, innerHeight } = window
        // 创建渲染
        const renderer = new THREE.WebGLRenderer()
        renderer.setSize(innerWidth, innerHeight)
        // 将画布放入dom
        oCanvas.current.appendChild(renderer.domElement)

        // 创建场景
        const scene = new THREE.Scene();
        // 创建相机
        const camera = new THREE.PerspectiveCamera(
            60,
            innerWidth / innerHeight,
            0.1,
            1200
        )
        camera.position.set(0, 0, 3)

        // 创建元素
        const geometry = new THREE.SphereGeometry( 1, 20, 12 )
        // 创建材质
        const material = new THREE.MeshBasicMaterial({
            color: "red",
            wireframe: true
        })
        // 创建网格
        const capsule = new THREE.Mesh(geometry, material)
        // 将网格添加到场景
        scene.add(capsule)
        
        // 动画
        const animate = () => { 
            capsule.rotation.x += 0.01
            capsule.rotation.y += 0.01
            // 渲染
            renderer.render(scene, camera)
            requestAnimationFrame(animate)
        }

        animate()
        

        
    })

    return (
        <div id="canvas" ref={oCanvas}></div>
    )
}

export default Canvas

// 02-vuethree/src/components/Canvas.vue
<script setup>
import { onMounted, ref } from 'vue'
import * as THREE from 'three'

// 创建场景
const scene = new THREE.Scene()
const { innerWidth, innerHeight } = window
const oCanvas = ref(null)

onMounted(()=>{
    init();
})
console.log(oCanvas);
function init() {
    // 创建相机并设置位置
    const camera = new THREE.PerspectiveCamera(
        60,
        innerWidth / innerHeight,
        0.1,
        1500
    )
    camera.position.set(0, 0, 3)
    // 创建渲染器并设置大小并挂载
    const renderer = new THREE.WebGLRenderer()
    renderer.setSize(innerWidth, innerHeight)
    oCanvas.value.appendChild(renderer.domElement)

    // 创建元素
    const geometry = new THREE.CapsuleGeometry(0.5, 0.5, 4, 8)
    // 创建材质
    const material = new THREE.MeshBasicMaterial({ 
        color: 0x00ff00, // 颜色
        wireframe: true // 线框渲染
    })
    // 创建网格，并将元素和材质嵌入
    const capsule = new THREE.Mesh(geometry, material)
    // 将网格添加到场景中
    scene.add(capsule)
    // 渲染
    const animate = () => { 
        capsule.rotation.x += 0.01
        capsule.rotation.y += 0.01
        // 渲染
        renderer.render(scene, camera)
        requestAnimationFrame(animate)
    }
    animate();
}






</script>

<template>
    <div id="canvas-box" ref="oCanvas"></div>

</template>
